"""Shared constants for DiGiTerra Flask app and blueprints."""
import os

# File upload
ALLOWED_EXTENSIONS = {"csv"}
FILE_SIZE_WARNING_MB = float(os.environ.get("DIGITERRA_WARN_UPLOAD_MB", "1"))
MAX_UPLOAD_MB = float(os.environ.get("DIGITERRA_MAX_UPLOAD_MB", "0"))
ENFORCE_UPLOAD_LIMIT = os.environ.get("DIGITERRA_ENFORCE_UPLOAD_LIMIT", "false").strip().lower() in {"1", "true", "yes", "on"}
CELL_COUNT_WARNING_LARGE = 1_000_000
CELL_COUNT_WARNING_MODERATE = 500_000
BYTES_PER_MB = 1024 * 1024

# Display
COLUMN_NAME_DISPLAY_LENGTH = 11
FILENAME_DISPLAY_LENGTH = 31

# Model training
DEFAULT_CV_FOLDS = 5
DEFAULT_SEARCH_ITERATIONS = 50
RANDOM_SEED_MAX = 1000

# Progress (SSE)
PROGRESS_STREAM_TIMEOUT_SECONDS = 3600
PROGRESS_UPDATE_INTERVAL_SECONDS = 0.5
PROGRESS_FINAL_UPDATE_DELAY_SECONDS = 0.5
PROGRESS_COMPLETE_THRESHOLD = 100

# HTTP
HTTP_OK = 200
HTTP_ACCEPTED = 202
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500
